# 重新抛出异常

```java
catch(Exception e){
    // ...
    throw e;
}
```